=== arunsathvik/KTAB/examples/reformpri/doc/reformpri.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Scenario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="desc" type="xs:string"/>
        <xs:element name="govBudget">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minExclusive value="0.0"/>
              <xs:maxInclusive value="100.0"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="outOfBudgetFactor">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minExclusive value="0.0"/>
              <xs:maxExclusive value="1.0"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="orderFactor">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minExclusive value="0.0"/>
              <xs:maxExclusive value="1.0"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element ref="Actors"/>
        <xs:element ref="Categories"/>
        <xs:element ref="Items"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Actors">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Actor" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Actor">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="capability">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minExclusive value="0.0"/>
              <xs:maxExclusive value="1000.0"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="ItemValues"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ItemValues">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="iVal" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="iVal">
    <xs:simpleType>
      <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="100.0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Categories">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="category" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="category">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Items">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Item" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Item">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="cost" >
   <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minExclusive value="0.0"/>
              <xs:maxInclusive value="100.0"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>        
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== arunsathvik/KTAB/examples/reformpri/doc/reformpri-ex01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
     Copyright (c) 2016, Copyright KAPSARC. Open Source MIT License.
     All rights reserved. This program and the accompanying materials
     are made available under the terms of the MIT Public License v1.0
     which accompanies this distribution, and is available at
     https://opensource.org/licenses/MIT
    
     Contributors:
         KAPSARC - initial API and implementation
 -->
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="reformpri.xsd">
  <name>RP-test-00</name>
  <desc>A very simple test of reform priority, using random numbers</desc>
  <govBudget>100</govBudget>
  <outOfBudgetFactor>0.1</outOfBudgetFactor>
  <orderFactor>0.85</orderFactor>
  <Actors>
    <Actor>
      <name>Alice</name>
      <description>One of the RP actors</description>
      <capability>72.2</capability>
      <ItemValues>
        <iVal>26</iVal>
        <iVal>63</iVal>
        <iVal>16</iVal>
        <iVal>46</iVal>
        <iVal>37</iVal>
      </ItemValues>
    </Actor>
    <Actor>
    
      <name>Bob</name>
      <description>One of the RP actors</description>
      <capability>48.2</capability>
      <ItemValues>
        <iVal>76</iVal>
        <iVal>22</iVal>
        <iVal>32</iVal>
        <iVal>81</iVal>
        <iVal>34</iVal>
      </ItemValues>
    </Actor>
    
    <Actor>
      <name>Carol</name>
      <description>One of the RP actors</description>
      <capability>78.2</capability>
      <ItemValues>
        <iVal>42</iVal>
        <iVal>15</iVal>
        <iVal>63</iVal>
        <iVal>34</iVal>
        <iVal>19</iVal>
      </ItemValues>
    </Actor>
    
    
    <Actor>
      <name>David</name>
      <description>One of the RP actors</description>
      <capability>37.3</capability>
      <ItemValues>
        <iVal>69</iVal>
        <iVal>41</iVal>
        <iVal>75</iVal>
        <iVal>63</iVal>
        <iVal>96</iVal>
      </ItemValues>
    </Actor>
    
    
    <Actor>
      <name>Elizabeth</name>
      <description>One of the RP actors</description>
      <capability>59.7</capability>
      <ItemValues>
        <iVal>84</iVal>
        <iVal>42</iVal>
        <iVal>100</iVal>
        <iVal>52</iVal>
        <iVal>67</iVal>
      </ItemValues>
    </Actor>
    
    
    <Actor>
      <name>Frank</name>
      <description>One of the RP actors</description>
      <capability>80.9</capability>
      <ItemValues>
        <iVal>78</iVal>
        <iVal>39</iVal>
        <iVal>36</iVal>
        <iVal>68</iVal>
        <iVal>50</iVal>
      </ItemValues>
    </Actor>
    
    
  </Actors>
  <Categories>
    <category>
      <name>First</name>
    </category>
    <category>
      <name>Second</name>
    </category>
    <category>
      <name>Third</name>
    </category>
    <category>
      <name>Fourth</name>
    </category>
    <category>
      <name>Fifth</name>
    </category>
  </Categories>
  <Items>
    <Item>
      <name>Ext</name>
      <cost>48.0</cost>
    </Item>
    <Item>
      <name>Ag</name>
      <cost>32.0</cost>
    </Item>
    <Item>
      <name>Man</name>
      <cost>41.0</cost>
    </Item>
    <Item>
      <name>Fin</name>
      <cost>27.0</cost>
    </Item>
    <Item>
      <name>Trn</name>
      <cost>45.0</cost>
    </Item>
  </Items>
</Scenario>
